import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '/public/material-theme/theme.css';
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  preload: true,
  fallback: [
    'Inter',
    '-apple-system', 'BlinkMacSystemFont', "Segoe UI", 'Roboto', "Helvetica Neue", 'Arial', 'sans-serif', "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol",
  ],
})

export const metadata: Metadata = {
  title: 'Adil Hanney',
  // TODO(adil192): Add description
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
